# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'#'Estimate conditional expectation using a Gaussian Kernel with changing bandwidth.
#'
#' @param y numeric vector
#' @param x numeric vector
#' @param x0 numeric vector
#' @param lambda double
#' @return conditional expectation
varKRS_cpp <- function(y, x, x0, lambda) {
    .Call(`_akrs_varKRS_cpp`, y, x, x0, lambda)
}

rcpp_hello_world <- function() {
    .Call(`_akrs_rcpp_hello_world`)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_akrs_RcppExport_registerCCallable', PACKAGE = 'akrs')
})
