# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform cross-validation for meanKRS function based on different lambdas.
#' 
#' @param y numeric vector
#' @param x numeric vector
#' @param lambdas numeric vector
#' @param k int
#' @return Vector of mean squared errors for each lamdba.
cv_meanKRS_cpp <- function(y, x, lambdas, k) {
    .Call(`_akrscv_cv_meanKRS_cpp`, y, x, lambdas, k)
}

rcpp_hello_world <- function() {
    .Call(`_akrscv_rcpp_hello_world`)
}

