// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_akrs_RCPPEXPORTS_H_GEN_
#define RCPP_akrs_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace akrs {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("akrs", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("akrs", "_akrs_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in akrs");
            }
        }
    }

    inline NumericVector meanKRS_cpp(const NumericVector y, const NumericVector x, const NumericVector x0, const double lambda) {
        typedef SEXP(*Ptr_meanKRS_cpp)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_meanKRS_cpp p_meanKRS_cpp = NULL;
        if (p_meanKRS_cpp == NULL) {
            validateSignature("NumericVector(*meanKRS_cpp)(const NumericVector,const NumericVector,const NumericVector,const double)");
            p_meanKRS_cpp = (Ptr_meanKRS_cpp)R_GetCCallable("akrs", "_akrs_meanKRS_cpp");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_meanKRS_cpp(Shield<SEXP>(Rcpp::wrap(y)), Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(x0)), Shield<SEXP>(Rcpp::wrap(lambda)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

}

#endif // RCPP_akrs_RCPPEXPORTS_H_GEN_
